# Install script for directory: H:/standalone/project/jvxAuNMyAlgorithm

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files/Project")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  exec_program("H:/standalone/env-dbg/sdk/bin/jvxExPropMat.exe H:/standalone/project/jvxAuNMyAlgorithm/codeGen/exports_node.pcg -o H:/standalone/build-algo/jvxAuNMyAlgorithm/m-files/+jvxAuNMyAlgorithm -ctp JVX_COMPONENT_AUDIO_NODE -cpf node")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  exec_program("H:/standalone/env-dbg/sdk/bin/jvxExPropMat.exe H:/standalone/env-dbg/sdk/software/templates/jvxComponents/jvxAudioNodes/CjvxAudioNode_pcg.pcg -o H:/standalone/build-algo/jvxAuNMyAlgorithm/m-files/+jvxAuNMyAlgorithm -ctp JVX_COMPONENT_AUDIO_NODE -cpf node")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "H:/standalone/env-dbg/runtime/matlab/m-files/audioProperties/+jvxAuNMyAlgorithm")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/runtime/matlab/m-files/audioProperties" TYPE DIRECTORY FILES "H:/standalone/build-algo/jvxAuNMyAlgorithm/m-files/+jvxAuNMyAlgorithm")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "release")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "H:/standalone/env-dbg/sdk/lib/jvxComponents-static/jvxAuNMyAlgorithm_static.lib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/sdk/lib/jvxComponents-static" TYPE STATIC_LIBRARY FILES "H:/standalone/build-algo/jvxAuNMyAlgorithm/Debug/jvxAuNMyAlgorithm_static.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "H:/standalone/env-dbg/sdk/lib/jvxComponents-static/jvxAuNMyAlgorithm_static.lib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/sdk/lib/jvxComponents-static" TYPE STATIC_LIBRARY FILES "H:/standalone/build-algo/jvxAuNMyAlgorithm/Release/jvxAuNMyAlgorithm_static.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "H:/standalone/env-dbg/sdk/lib/jvxComponents-static/jvxAuNMyAlgorithm_static.lib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/sdk/lib/jvxComponents-static" TYPE STATIC_LIBRARY FILES "H:/standalone/build-algo/jvxAuNMyAlgorithm/MinSizeRel/jvxAuNMyAlgorithm_static.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "H:/standalone/env-dbg/sdk/lib/jvxComponents-static/jvxAuNMyAlgorithm_static.lib")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/sdk/lib/jvxComponents-static" TYPE STATIC_LIBRARY FILES "H:/standalone/build-algo/jvxAuNMyAlgorithm/RelWithDebInfo/jvxAuNMyAlgorithm_static.lib")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "release")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "H:/standalone/env-dbg/sdk/include/jvxComponents-static/jvxAuNMyAlgorithm.h")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/sdk/include/jvxComponents-static" TYPE FILE FILES "H:/standalone/build-algo/jvxAuNMyAlgorithm/jvxAuNMyAlgorithm.h")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "H:/standalone/env-dbg/runtime/jvxComponents/jvxAuNMyAlgorithm.dll")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/runtime/jvxComponents" TYPE SHARED_LIBRARY FILES "H:/standalone/build-algo/jvxAuNMyAlgorithm/Debug/jvxAuNMyAlgorithm.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "H:/standalone/env-dbg/runtime/jvxComponents/jvxAuNMyAlgorithm.dll")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/runtime/jvxComponents" TYPE SHARED_LIBRARY FILES "H:/standalone/build-algo/jvxAuNMyAlgorithm/Release/jvxAuNMyAlgorithm.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "H:/standalone/env-dbg/runtime/jvxComponents/jvxAuNMyAlgorithm.dll")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/runtime/jvxComponents" TYPE SHARED_LIBRARY FILES "H:/standalone/build-algo/jvxAuNMyAlgorithm/MinSizeRel/jvxAuNMyAlgorithm.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "H:/standalone/env-dbg/runtime/jvxComponents/jvxAuNMyAlgorithm.dll")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
        message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/runtime/jvxComponents" TYPE SHARED_LIBRARY FILES "H:/standalone/build-algo/jvxAuNMyAlgorithm/RelWithDebInfo/jvxAuNMyAlgorithm.dll")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "release")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "H:/standalone/env-dbg/sdk/")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/sdk" TYPE DIRECTORY FILES "H:/standalone/project/jvxAuNMyAlgorithm/install/")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "release")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "H:/standalone/env-dbg/runtime/matlab/m-files/subprojects-audionode/+jvxAuNMyAlgorithm/")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/runtime/matlab/m-files/subprojects-audionode/+jvxAuNMyAlgorithm" TYPE DIRECTORY FILES "H:/standalone/env-dbg/sdk/software/codeFragments/matlab/m-files/host-hooks/")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "release")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "H:/standalone/env-dbg/runtime/matlab/m-files/subprojects-audionode/+jvxAuNMyAlgorithm/")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/runtime/matlab/m-files/subprojects-audionode/+jvxAuNMyAlgorithm" TYPE DIRECTORY FILES "H:/standalone/env-dbg/sdk/software/codeFragments/matlab/m-files/local-calls/")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "release")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "H:/standalone/env-dbg/runtime/matlab/m-files/subprojects-audionode/+jvxAuNMyAlgorithm/jvx_init_callback.m")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "H:/standalone/env-dbg/runtime/matlab/m-files/subprojects-audionode/+jvxAuNMyAlgorithm" TYPE FILE FILES "H:/standalone/build-algo/jvxAuNMyAlgorithm/jvx_init_callback.m")
endif()

