#ifndef __TJVXREPORTTEXTMESSAGE_H__
#define __TJVXREPORTTEXTMESSAGE_H__

typedef enum
{
	JVX_REPORT_PRIORITY_NONE,
	JVX_REPORT_PRIORITY_ERROR,
	JVX_REPORT_PRIORITY_WARNING,
	JVX_REPORT_PRIORITY_SUCCESS,
	JVX_REPORT_PRIORITY_INFO
} jvxReportPriority;

typedef enum
{
	JVX_REPORT_REQUEST_TRY_TRIGGER_STOP_SEQUENCER,
	JVX_REPORT_REQUEST_TRY_TRIGGER_START_SEQUENCER,
    JVX_REPORT_REQUEST_UPDATE_WINDOW, 
	JVX_REPORT_REQUEST_UPDATE_PROPERTY_VIEWER, 
	JVX_REPORT_REQUEST_USER_MESSAGE
} jvxCommandRequestType;

#endif