	{	"jvx_camera_config_int_string"			,	JVX_PROPERTIES_OFFSET_PRODUCT + 11				,	JVX_DATAFORMAT_STRING			,	1	, JVX_PROPERTY_DECODER_FILENAME_OPEN},
	{	"jvx_camera_config_ext_string"			,	JVX_PROPERTIES_OFFSET_PRODUCT + 12				,	JVX_DATAFORMAT_STRING			,	1	, JVX_PROPERTY_DECODER_FILENAME_OPEN},
	{	"jvx_num_circ_buffers_int32"			,	JVX_PROPERTIES_OFFSET_PRODUCT + 13				,	JVX_DATAFORMAT_16BIT_LE			,	1	, JVX_PROPERTY_DECODER_NONE},
