#ifndef __TJVXWEBSERVER_H__
#define __TJVXWEBSERVER_H__
	
typedef enum 
{
	JVX_WEB_SERVER_RESPONSE_UNKNOWN = 0,
	JVX_WEB_SERVER_RESPONSE_JSON = 1
} jvxWebServerResponseType;

typedef enum
{
	JVX_WEB_SERVER_UNKNOWN_HANDLER = 0,
	JVX_WEB_SERVER_SYSTEM_REQUEST_HANDLER = 0x1,
	JVX_WEB_SERVER_URI_GET_HANDLER = 0x2,
	JVX_WEB_SERVER_URI_POST_HANDLER = 0x4,

	JVX_WEB_SERVER_URI_WEBSOCKET_CONNECT_HANDLER = 0x8,
	JVX_WEB_SERVER_URI_WEBSOCKET_READY_HANDLER = 0x10,
	JVX_WEB_SERVER_URI_WEBSOCKET_DATA_HANDLER = 0x20,
	JVX_WEB_SERVER_URI_WEBSOCKET_CLOSE_HANDLER = 0x40
}jvxWebServerHandlerPurpose;

typedef enum 
{
	JVX_WEBSOCKET_OPCODE_CONTINUATION = 0x0,
	JVX_WEBSOCKET_OPCODE_TEXT = 0x1,
	JVX_WEBSOCKET_OPCODE_BINARY = 0x2,
	JVX_WEBSOCKET_OPCODE_CONNECTION_CLOSE = 0x8,
	JVX_WEBSOCKET_OPCODE_PING = 0x9,
	JVX_WEBSOCKET_OPCODE_PONG = 0xa
} jvxWebServerWebSocketFrameType;

#endif
