#ifndef _HJVXCOMPONENTTYPESELECTORS_H__
#define _HJVXCOMPONENTTYPESELECTORS_H__

static std::string jvxComponentType_selectors[JVX_COMPONENT_LIMIT] = 
{
	"JVX_COMPONENT_UNKNOWN", 
    "JVX_COMPONENT_AUDIO_TECHNOLOGY", 
    "JVX_COMPONENT_AUDIO_DEVICE", 
    "JVX_COMPONENT_AUDIO_NODE", 
    "JVX_COMPONENT_EXTERNAL_CONTROLLER_TECHNOLOGY", 
    "JVX_COMPONENT_EXTERNAL_CONTROLLER_DEVICE", 
    "JVX_COMPONENT_HOST", 
	"JVX_COMPONENT_RT_AUDIO_FILE_READER,", 
	"JVX_COMPONENT_RT_AUDIO_FILE_WRITER,", 
	"JVX_COMPONENT_RESAMPLER, ", 
	"JVX_COMPONENT_DATACONVERTER,", 
    "JVX_COMPONENT_DATALOGGER", 
    "JVX_COMPONENT_DATALOGREADER", 
    "JVX_COMPONENT_RS232", 
    "JVX_COMPONENT_CONFIG_PROCESSOR", 
	"JVX_COMPONENT_EXTERNAL_CALL", 
    "JVX_COMPONENT_THREADCONTROLLER"
};

#endif