# set platform variables
message("--> OS is ${CMAKE_SYSTEM_NAME}")
if(NOT DEFINED CMAKE_SIZEOF_VOID_P)
  set(CMAKE_SIZEOF_VOID_P  4)
  message(WARNING "XX> Platform type not set, defaulting to 32 Bit")
endif()
if(CMAKE_SIZEOF_VOID_P EQUAL 4)
  message("--> 32 Bit platform")
  set(JVX_PLATFORM "32bit")
else(CMAKE_SIZEOF_VOID_P EQUAL 4)
  message("--> 64 Bit platform")
  set(JVX_PLATFORM "64bit")
endif(CMAKE_SIZEOF_VOID_P EQUAL 4)
if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
  if(IOS)
    set(JVX_OS "ios")
  else(IOS)
    set(JVX_OS "macosx")
  endif(IOS)
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
  set(JVX_OS "windows")
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
  set(JVX_OS "linux")
else()
  message(FATAL_ERROR "Your OS is not supported")
endif()

# include platform specific stuff
include(${JVX_CMAKE_DIR}/${JVX_OS}.cmake)
