# build unstable targets only with Unstable build types
if((NOT JVX_DEPLOY_UNSTABLE) AND IS_UNSTABLE)
  message("Excluding unstable target ${JVX_TARGET_NAME} from build.")
  return()
endif()

if(BUILD_MEX_OCTAVE AND BUILD_MEX_MATLAB)
  message(FATAL_ERROR "building matlab and octave mex files at once is not yet supported...")
endif()

# do not start mex files with lib...
set(CMAKE_SHARED_LIBRARY_PREFIX "")

if(IS_UNSTABLE)
  set(INSTALL_COMPONENT "unstable")
else()
  set(INSTALL_COMPONENT "release")
endif()

###
# Octave
###
if(BUILD_MEX_OCTAVE)

  message("    > MEX-File (octave)")

  include_directories(${OCTAVE_INCLUDE_PATH})
  link_directories(${OCTAVE_PATH_LIB})
  add_library(${JVX_TARGET_NAME} SHARED ${LOCAL_SOURCES})
  target_compile_definitions(${JVX_TARGET_NAME} PRIVATE ${LOCAL_COMPILE_DEFINITIONS})
  set_target_properties(${JVX_TARGET_NAME} PROPERTIES
    COMPILE_FLAGS "${JVX_CXX_FLAGS_MEX_OCTAVE} ${JVX_CMAKE_CXX_FLAGS_SHARED} ${LOCAL_CXX_FLAGS}"
    LINK_FLAGS "${JVX_CMAKE_LINKER_FLAGS_MEX} ${LOCAL_LINKER_FLAGS}"
    SUFFIX "${OCTAVE_MEX_SUFFIX}")
  target_link_libraries(${JVX_TARGET_NAME} ${LOCAL_LIBS} ${JVX_SYSTEM_OCTAVE_MEX_LIBRARIES} ${JVX_SYSTEM_LIBRARIES})
  jvx_displayFlags(${JVX_TARGET_NAME})

  # installation
  if(INSTALL_TARGET_NAME_OCTAVE)
    set_target_properties(${JVX_TARGET_NAME} PROPERTIES OUTPUT_NAME ${INSTALL_TARGET_NAME_OCTAVE})
  endif(INSTALL_TARGET_NAME_OCTAVE)
  install(TARGETS ${JVX_TARGET_NAME}
		RUNTIME DESTINATION ${INSTALL_PATH_OCTAVE}
        LIBRARY DESTINATION ${INSTALL_PATH_OCTAVE}
		COMPONENT ${INSTALL_COMPONENT})
		
  FOREACH(LOCAL_DIR_ENTRY ${LOCAL_M_FILES_SOURCE_DIR})
	install(DIRECTORY ${LOCAL_DIR_ENTRY}/ DESTINATION ${INSTALL_PATH_OCTAVE}/m-files COMPONENT ${INSTALL_COMPONENT})
  ENDFOREACH()

  if(LOCAL_IMAGES_SOURCE_DIR)
    install(DIRECTORY ${LOCAL_IMAGES_SOURCE_DIR}/ DESTINATION ${INSTALL_PATH_IMAGES} COMPONENT ${INSTALL_COMPONENT})
  endif(LOCAL_IMAGES_SOURCE_DIR)
  if(LOCAL_START_SCRIPT)
    install(PROGRAMS ${CMAKE_CURRENT_SOURCE_DIR}/../../scripts/${JVX_OS}/${JVX_PLATFORM}/${LOCAL_START_SCRIPT}${JVX_SCRIPT_EXTENSION} DESTINATION ${INSTALL_PATH_SCRIPTS} COMPONENT ${INSTALL_COMPONENT})
  else(LOCAL_START_SCRIPT)
    if(CONFIGURE_LOCAL_START_SCRIPT)
      configure_file(${JVX_BASE_ROOT}/software/templates/scripts/startOctave${JVX_SCRIPT_EXTENSION}.${JVX_OS}.in ${CMAKE_CURRENT_BINARY_DIR}/start-${JVX_TARGET_NAME}${JVX_SCRIPT_EXTENSION})
      install(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/start-${JVX_TARGET_NAME}${JVX_SCRIPT_EXTENSION} DESTINATION ${INSTALL_PATH_SCRIPTS} COMPONENT ${INSTALL_COMPONENT})
    endif(CONFIGURE_LOCAL_START_SCRIPT)
  endif(LOCAL_START_SCRIPT)

endif()

###
# Matlab
###
if(BUILD_MEX_MATLAB)
  message("    > MEX-File (matlab) ${MATLAB_PATH_LIB}")

  include_directories(${Matlab_INCLUDE_DIRS})
  link_directories(${MATLAB_PATH_LIB})
  add_library(${JVX_TARGET_NAME} SHARED ${LOCAL_SOURCES})
  target_compile_definitions(${JVX_TARGET_NAME} PRIVATE ${LOCAL_COMPILE_DEFINITIONS})
  set_target_properties(${JVX_TARGET_NAME} PROPERTIES
    COMPILE_FLAGS "${JVX_CXX_FLAGS_MEX_MATLAB} ${JVX_CMAKE_CXX_FLAGS_SHARED} ${LOCAL_CXX_FLAGS}"
    LINK_FLAGS "${JVX_CMAKE_LINKER_FLAGS_MEX} ${LOCAL_LINKER_FLAGS}"
    SUFFIX "${MATLAB_MEX_SUFFIX}")
  target_link_libraries(${JVX_TARGET_NAME} ${LOCAL_LIBS} ${JVX_SYSTEM_MATLAB_MEX_LIBRARIES} ${JVX_SYSTEM_LIBRARIES})
  jvx_displayFlags(${JVX_TARGET_NAME})

  # installation
  if(INSTALL_TARGET_NAME_MATLAB)
    set_target_properties(${JVX_TARGET_NAME} PROPERTIES OUTPUT_NAME ${INSTALL_TARGET_NAME_MATLAB})
  endif(INSTALL_TARGET_NAME_MATLAB)
  install(TARGETS ${JVX_TARGET_NAME}
		RUNTIME DESTINATION ${INSTALL_PATH_MATLAB}
        LIBRARY DESTINATION ${INSTALL_PATH_MATLAB}
		COMPONENT ${INSTALL_COMPONENT})
  
  FOREACH(LOCAL_DIR_ENTRY ${LOCAL_M_FILES_SOURCE_DIR})
	install(DIRECTORY ${LOCAL_DIR_ENTRY}/ DESTINATION ${INSTALL_PATH_MATLAB}/m-files COMPONENT ${INSTALL_COMPONENT})
  ENDFOREACH()

  if(LOCAL_IMAGES_SOURCE_DIR)
	install(DIRECTORY ${LOCAL_IMAGES_SOURCE_DIR}/ DESTINATION ${INSTALL_PATH_IMAGES} COMPONENT ${INSTALL_COMPONENT})
  endif(LOCAL_IMAGES_SOURCE_DIR)
  if(LOCAL_START_SCRIPT)
      install(PROGRAMS ${CMAKE_CURRENT_SOURCE_DIR}/../../scripts/${JVX_OS}/${JVX_PLATFORM}/${LOCAL_START_SCRIPT}${JVX_SCRIPT_EXTENSION} DESTINATION ${INSTALL_PATH_SCRIPTS})
  else(LOCAL_START_SCRIPT COMPONENT ${INSTALL_COMPONENT})
	if(CONFIGURE_LOCAL_START_SCRIPT)
		configure_file(${JVX_BASE_ROOT}/software/templates/scripts/startMatlab${JVX_SCRIPT_EXTENSION}.${JVX_OS}.in ${CMAKE_CURRENT_BINARY_DIR}/start-${JVX_TARGET_NAME}${JVX_SCRIPT_EXTENSION})
		install(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/start-${JVX_TARGET_NAME}${JVX_SCRIPT_EXTENSION} DESTINATION ${INSTALL_PATH_SCRIPTS} COMPONENT ${INSTALL_COMPONENT})
	endif(CONFIGURE_LOCAL_START_SCRIPT)
  endif(LOCAL_START_SCRIPT)

endif()

###
# error
###
if(NOT BUILD_MEX_OCTAVE AND NOT BUILD_MEX_MATLAB)
  message(FATAL_ERROR "Library module must define BUILD_MEX_OCTAVE or BUILD_MEX_MATLAB")
endif()
